# Generated by Django 4.0.4 on 2022-05-23 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_image', models.ImageField(default='images/profile/default.jpeg', upload_to='images/profile')),
                ('bio', models.TextField()),
                ('website_url', models.CharField(blank=True, max_length=120, null=True)),
                ('facebook_url', models.CharField(blank=True, max_length=120, null=True)),
                ('whatsapp_url', models.CharField(blank=True, max_length=120, null=True)),
                ('telegram_url', models.CharField(blank=True, max_length=120, null=True)),
                ('twitter_url', models.CharField(blank=True, max_length=120, null=True)),
                ('instagram_url', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
