# Generated by Django 4.0.4 on 2022-05-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='')),
                ('email', models.EmailField(max_length=128, verbose_name='')),
                ('subject', models.CharField(blank=True, max_length=128, null=True, verbose_name='')),
                ('message', models.TextField(max_length=2800, verbose_name='')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
