# Generated by Django 4.0.4 on 2022-05-19 21:36

import ckeditor.fields
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='максимум 160 символов', max_length=160, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('salary', models.CharField(blank=True, max_length=30)),
                ('format', models.CharField(blank=True, max_length=30)),
                ('client', models.TextField(blank=True)),
                ('duties', ckeditor.fields.RichTextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('offer', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('contacts', models.BooleanField(default=False)),
                ('onTop', models.BooleanField(default=False)),
                ('author', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vacancy id, slug, namespace',
                'verbose_name_plural': 'Vacancies id, slug, namespaces',
            },
        ),
    ]
