# Generated by Django 4.0.4 on 2022-05-19 22:19

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='client',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='offer',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirements',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
