# Generated by Django 4.0.4 on 2022-05-19 22:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_alter_vacancy_client_alter_vacancy_offer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='offer',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirements',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
