# Generated by Django 4.0.4 on 2022-05-20 14:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_alter_vacancy_offer_alter_vacancy_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='date_published',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='entryСontent',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='isPublished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(max_length=160, verbose_name='Название'),
        ),
    ]
