# Generated by Django 4.0.4 on 2022-05-21 08:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_vacancy_date_published_vacancy_entryсontent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='city',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='client',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='image',
            field=models.IntegerField(choices=[(1, 'Blog1'), (2, 'Blog2'), (3, 'Blog3'), (4, 'Blog4'), (5, 'Blog5'), (6, 'Blog6'), (7, 'Blog7'), (8, 'Blog8'), (9, 'Blog9')], default=1),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='entryСontent',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Краткое описание вакансии или клиента'),
        ),
    ]
