# Generated by Django 4.0.4 on 2022-05-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_rename_city_vacancy_location_remove_vacancy_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
