# Generated by Django 4.0.4 on 2022-05-21 13:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0006_alter_vacancy_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Vacancy', 'verbose_name_plural': 'Vacancies'},
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='duties',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='requirements',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Полноее описание вакансии, обязанности, требования, условия'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='contacts',
            field=models.BooleanField(default=False, verbose_name='Указать контакты рекрутера'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='entryСontent',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Краткое описание вакансии, проекта или клиента'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='format',
            field=models.CharField(blank=True, max_length=30, verbose_name='Занятость, в штат'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='location',
            field=models.CharField(blank=True, max_length=30, verbose_name='город - офис, удалённо'),
        ),
    ]
