# Generated by Django 4.0.4 on 2022-05-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0007_alter_vacancy_options_remove_vacancy_date_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='onTop',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='contacts',
            field=models.BooleanField(default=True, verbose_name='Указать контакты рекрутера'),
        ),
    ]
