# Generated by Django 4.0.4 on 2022-05-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0008_remove_vacancy_ontop_alter_vacancy_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='tags',
            field=models.TextField(blank=True),
        ),
    ]
