# Generated by Django 4.0.4 on 2022-05-22 00:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0010_vacancy_ontop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='onTop',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Полноее описание вакансии: обязанности, требования, условия'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='format',
            field=models.CharField(blank=True, max_length=30, verbose_name='Занятость / в штат'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='location',
            field=models.CharField(blank=True, max_length=30, verbose_name='город - офис / удалённо'),
        ),
    ]
