# Generated by Django 4.0.4 on 2022-05-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0011_remove_vacancy_ontop_alter_vacancy_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='isOnTop',
            field=models.BooleanField(default=False),
        ),
    ]
