# Generated by Django 4.0.4 on 2022-05-23 05:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0012_vacancy_isontop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='isPublished',
            new_name='is_published',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Полноее описание вакансии: обязанности, требования, условия.'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='entryСontent',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Краткое описание вакансии, проекта или клиента. / Превью.'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='image',
            field=models.IntegerField(choices=[(1, 'Blog1'), (2, 'Blog2'), (3, 'Blog3'), (4, 'Blog4'), (5, 'Blog5'), (6, 'Blog6'), (7, 'Blog7'), (8, 'Blog8'), (9, 'Blog9')], default=1, verbose_name='Выбор картинки для вакансии'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='isOnTop',
            field=models.BooleanField(default=False, verbose_name='Разместить на главной странице'),
        ),
    ]
