# Generated by Django 4.0.4 on 2022-05-23 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0013_rename_ispublished_vacancy_is_published_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='isOnTop',
            new_name='is_on_top',
        ),
    ]
