# Generated by Django 4.0.4 on 2022-05-23 21:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0014_rename_isontop_vacancy_is_on_top'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Полное описание вакансии: обязанности, требования, условия.'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='is_on_top',
            field=models.BooleanField(default=False, verbose_name='На главной странице'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
    ]
