# Generated by Django 4.0.4 on 2022-05-25 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0015_alter_vacancy_body_alter_vacancy_is_on_top_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('telegram_url', models.URLField(blank=True, max_length=120, null=True)),
                ('whatsapp_url', models.URLField(blank=True, max_length=120, null=True)),
                ('linkedin_url', models.URLField(blank=True, max_length=120, null=True)),
                ('cover_letter', models.TextField(verbose_name='Cover letter')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('salary', models.CharField(blank=True, max_length=30)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_application', to='vacancies.vacancy')),
            ],
            options={
                'verbose_name': 'Отклик на вакансию',
                'verbose_name_plural': 'Отклики на вакансию',
            },
        ),
    ]
