# Generated by Django 4.0.4 on 2022-05-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0018_alter_jobapplication_cover_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='github_url',
            field=models.URLField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.TextField(blank=True, null=True, verbose_name='Cover letter'),
        ),
    ]
