# Generated by Django 4.0.4 on 2022-05-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0020_alter_jobapplication_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='github_url',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='telegram_url',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='whatsapp_url',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
