# Generated by Django 4.0.4 on 2022-05-27 06:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0022_jobapplication_handout_alter_jobapplication_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='myfile',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['txt', 'pdf', 'doc', 'docx'], message='myfile должен быть txt, doc, docx, pdf файл')]),
        ),
    ]
