# Generated by Django 4.0.4 on 2022-05-27 07:20

from django.db import migrations, models
import vacancies.formatChecker


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0023_jobapplication_myfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='myfile',
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='handout',
            field=vacancies.formatChecker.ContentTypeRestrictedFileField(blank=True, help_text='Загрузить резюме в формате txt, doc, docx, pdf', null=True, upload_to='resumes/', verbose_name='Загрузить резюме*'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(help_text='Загрузить резюме в формате txt, doc, docx, pdf', upload_to='resumes/', verbose_name='Загрузить резюме*'),
        ),
    ]
