# Generated by Django 4.0.4 on 2022-05-27 07:24

from django.db import migrations
import vacancies.formatChecker


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0024_remove_jobapplication_myfile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='handout',
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=vacancies.formatChecker.ContentTypeRestrictedFileField(blank=True, help_text='Загрузить резюме в формате txt, doc, docx, pdf', null=True, upload_to='resumes/', verbose_name='Загрузить резюме*'),
        ),
    ]
